'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8745
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Profile1

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''WeekEnding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WeekEnding As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Job control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Job As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''StartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''EndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EndDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Organisation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Organisation As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Department As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ReportTo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportTo1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ReportTo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportTo2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MondayDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MondayDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MondayStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MondayStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MondayBreakStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MondayBreakStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MondayBreakFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MondayBreakFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MondayFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MondayFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MondayTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MondayTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''MondayLeave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MondayLeave As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TuesdayDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TuesdayDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TuesdayStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TuesdayStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TuesdayBreakStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TuesdayBreakStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TuesdayBreakFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TuesdayBreakFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TuesdayFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TuesdayFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TuesdayTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TuesdayTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TuesdayLeave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TuesdayLeave As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''WednesdayDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WednesdayDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''WednesdayStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WednesdayStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''WednesdayBreakStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WednesdayBreakStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''WednesdayBreakFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WednesdayBreakFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''WednesdayFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WednesdayFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''WednesdayTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WednesdayTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''WednesdayLeave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WednesdayLeave As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ThursdayDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThursdayDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ThursdayStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThursdayStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ThursdayBreakStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThursdayBreakStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ThursdayBreakFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThursdayBreakFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ThursdayFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThursdayFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ThursdayTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThursdayTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ThursdayLeave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ThursdayLeave As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FridayDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FridayDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FridayStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FridayStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FridayBreakStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FridayBreakStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FridayBreakFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FridayBreakFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FridayFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FridayFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FridayTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FridayTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''FridayLeave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FridayLeave As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SaturdayDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaturdayDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SaturdayStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaturdayStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SaturdayBreakStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaturdayBreakStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SaturdayBreakFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaturdayBreakFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SaturdayFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaturdayFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SaturdayTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaturdayTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SaturdayLeave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaturdayLeave As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SundayDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SundayDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SundayStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SundayStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SundayBreakStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SundayBreakStart As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SundayBreakFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SundayBreakFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SundayFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SundayFinish As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SundayTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SundayTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SundayLeave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SundayLeave As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''WeekTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WeekTotal As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As portal_1._3.Profile
        Get
            Return CType(MyBase.Master, portal_1._3.Profile)
        End Get
    End Property
End Class
