'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8784
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ProfileInfo1

    '''<summary>
    '''new_candidates_onboarding_job_info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents new_candidates_onboarding_job_info As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''litFName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litFName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandNameTtile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandNameTtile As Global.StayinFront.Web.UI.StayinFrontDataSource

    '''<summary>
    '''title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents title As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''NewCandProfiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewCandProfiles As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''isNewUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents isNewUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''first_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents first_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''middle_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents middle_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''last_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents last_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''phone_l_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phone_l_a As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''phone_l_n control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phone_l_n As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''phone_l_a2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phone_l_a2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''phone_l_n2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phone_l_n2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''birthday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents birthday As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents address As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''city control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents city As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''postCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents postCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SIFConn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SIFConn As Global.StayinFront.Web.UI.Connection

    '''<summary>
    '''SIFCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SIFCountry As Global.StayinFront.Web.UI.StayinFrontDataSource

    '''<summary>
    '''ddlCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCountry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''birthPlace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents birthPlace As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''linkedin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents linkedin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''skype_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents skype_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''interests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents interests As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''marital_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents marital_status As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''par_occ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents par_occ As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''driving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents driving As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ownTransport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ownTransport As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''smoker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents smoker As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''AltNameTtile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AltNameTtile As Global.StayinFront.Web.UI.StayinFrontDataSource

    '''<summary>
    '''AltTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AltTitle As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''alt_first_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alt_first_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''alt_middle_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alt_middle_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''alt_last_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alt_last_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''alt_phone_l_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alt_phone_l_a As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''alt_phone_l_l control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alt_phone_l_l As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''alt_rel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alt_rel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''w_phone_l_a control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents w_phone_l_a As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''w_phone_l_l control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents w_phone_l_l As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''w_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents w_email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''currEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currEmp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''currPos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currPos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''currSal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currSal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sal_sought control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sal_sought As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''currAgen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currAgen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''temp_sought control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents temp_sought As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''notice_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notice_time As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''next_btn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents next_btn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As portal_1._3.NewUserMaster
        Get
            Return CType(MyBase.Master, portal_1._3.NewUserMaster)
        End Get
    End Property
End Class
