'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8784
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class NewUserMaster

    '''<summary>
    '''NewUserTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewUserTitle As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''NewUserScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewUserScripts As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''NewUserMenuL1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewUserMenuL1 As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''NewUserMenuL2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewUserMenuL2 As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''form_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form_container As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NewUserContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewUserContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As portal_1._3.Portal
        Get
            Return CType(MyBase.Master, portal_1._3.Portal)
        End Get
    End Property
End Class
