'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8745
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Profile1

    '''<summary>
    '''first_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents first_name As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''last_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents last_name As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandWorkHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandWorkHistory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CandidateSkills control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidateSkills As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''candidateAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents candidateAddress As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''candidateCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents candidateCity As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''candidatePostCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents candidatePostCode As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''candidateDOB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents candidateDOB1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''candidateDOB2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents candidateDOB2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''candidateDOB3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents candidateDOB3 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidatePlaceOfBirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidatePlaceOfBirth As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''candidateLinkedIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents candidateLinkedIn As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''candidateFacebook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents candidateFacebook As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''candidateSkypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents candidateSkypeName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''candidateMartialStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents candidateMartialStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidatePartnerOcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidatePartnerOcc As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''candidateInterests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents candidateInterests As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidateOwnTransport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidateOwnTransport As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidateDriversLicense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidateDriversLicense As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidateSmoker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidateSmoker As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidatesEmergencyContact2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidatesEmergencyContact2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidatesEmergencyContact3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidatesEmergencyContact3 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidatesEmergencyContactPhone1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidatesEmergencyContactPhone1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidatesEmergencyContactPhone2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidatesEmergencyContactPhone2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidatesEmergencyContactRelationship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidatesEmergencyContactRelationship As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidatesWorkPhone1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidatesWorkPhone1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidatesWorkPhone2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidatesWorkPhone2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidatesWorkPhone3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidatesWorkPhone3 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidatesWorlEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidatesWorlEmail As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''CandidatesReferees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CandidatesReferees As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As portal_1._3.Profile
        Get
            Return CType(MyBase.Master, portal_1._3.Profile)
        End Get
    End Property
End Class
